language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - CATKIN_LINT=pedantic
    - NOT_TEST_DOWNSTREAM=true
    - PARALLEL_TESTS=true
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=true
  matrix:
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=file
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
