name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: "0 23 * * *" # everyday at 11pm
  

jobs:
  industrial_ci:
    timeout-minutes: 30
    env:
      ADDITIONAL_DEBS: git-core openssh-client openssh-server curl
      AFTER_INIT: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && git config --global url."https://token:${{secrets.GITHUBPAT}}@github.com/".insteadOf "https://github.com/" && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs -y && cd $HOME && git lfs install && cd -
      CATKIN_LINT: pedantic
      NOT_TEST_DOWNSTREAM: true
      PYLINT_ARGS: "--output-format=parseable --errors-only --ignored-modules=tf2_ros"
      PYLINT2_CHECK: true
      PYLINT3_CHECK: false
      PARALLEL_TESTS: true
      ROS_REPO: ros
      VERBOSE_OUTPUT: false
      VERBOSE_TESTS: true
      UPSTREAM_WORKSPACE: .travis.rosinstall
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic}
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic, BEFORE_SETUP_TARGET_WORKSPACE: 'apt-get install python-is-python3'}
    name: ${{matrix.env.ROS_DISTRO}} # names the matrix jobs base on ROS_DISTRO (without all other env variables which are set in the matrix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: 'fmessmer/industrial_ci@master_pylint'
        env: ${{matrix.env}}
